import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import {Metadata} from "next";
import {ToastContainer} from "react-toastify";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "ETodo",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={"dark"} lang="en">
        <head>
            <script src="https://accounts.google.com/gsi/client" async defer></script>
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col `}
        >
        <NavBar/>
        <ToastContainer/>
        <div className={"bg-gray-400 grow h-full flex duration-300 transition-all dark:bg-gray-600"}>
            {children}
        </div>
        </body>
        </html>
    );
}
